FROM python:3.9-alpine

WORKDIR /usr/src/app

COPY movie_api.py /usr/src/app/
COPY movies.py /usr/src/app/
COPY requirements.txt /usr/src/app/

RUN pip install -r requirements.txt

CMD python movie_api.py